services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  producer:
    build: .
    # Pass the shared volume path
    command: python producer.py --verbose --host mosquitto --bin-id "urn:wastebin:bin-01"
    volumes:
      - ./data:/app/data
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
    depends_on:
      - mosquitto

  api:
    build: .
    # Crucial: Tell the API where to find the broker and the shared data
    command: python api.py
    environment:
      - MQTT_HOST=mosquitto
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    depends_on:
      - mosquitto